# Generated by Django 3.1.2 on 2021-04-08 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0089_auto_20200902_1249'),
        ('product', '0129_add_product_types_and_attributes_perm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_received_in_wharehouse', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_order', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(max_length=255)),
                ('quantity_returned', models.IntegerField(default=0)),
                ('return_type', models.CharField(choices=[('EXCHANGE', 'EXCHANGE'), ('REFUND', 'REFUND')], default='REFUND', max_length=255)),
                ('return_sku', models.CharField(max_length=255)),
                ('exchange_sku', models.CharField(max_length=255)),
                ('returned_to_stock', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_quantity', models.IntegerField(default=0)),
                ('rejected_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('exchange_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_variant', to='product.productvariant')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_line', to='order.orderline')),
                ('return_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returns.returnheader')),
                ('return_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_variant', to='product.productvariant')),
            ],
        ),
    ]
