# Generated by Django 3.1.2 on 2021-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnline',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='returnline',
            name='returned_to_stock',
        ),
        migrations.AddField(
            model_name='returnheader',
            name='misc_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='returnheader',
            name='status',
            field=models.CharField(default='open', max_length=255),
        ),
        migrations.AddField(
            model_name='returnline',
            name='exchange_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnline',
            name='reject_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnline',
            name='returned_to_stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='returnline',
            name='exchange_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
